qa_dict = {
    "What is the capital of France?": "paris",
    "What is 2 + 2?": "4",
    "Who wrote '1984'?": "george orwell",
    "What is the largest planet in our solar system?": "jupiter",
    "Who painted the Mona Lisa?": "leonardo da vinci",
    "What is the boiling point of water in Celsius?": "100°c",
    "What is the currency of Japan?": "yen",
    "What is the tallest mountain in the world?": "mount everest",
    "Who is the current president of the United States?": "joe biden",
    "What is the chemical symbol for gold?": "au",
    "How many continents are there?": "7",
    "Who developed the theory of relativity?": "albert einstein",
    "What is the largest ocean on Earth?": "pacific ocean",
    "What is the smallest country in the world?": "vatican city",
    "Who was the first man to walk on the Moon?": "neil armstrong",
    "What is the hardest natural substance on Earth?": "diamond",
    "What is the main ingredient in guacamole?": "avocado",
    "How many bones are in the adult human body?": "206",
    "What is the longest river in the world?": "amazon river",
    "What is the fastest land animal?": "cheetah",
    "Who invented the light bulb?": "thomas edison",
    "What is the largest animal on Earth?": "blue whale",
    "What is the capital of Canada?": "ottawa",
    "Which planet is known as the Red Planet?": "mars",
    "What is the currency of the United Kingdom?": "pound sterling",
    "Who wrote 'Romeo and Juliet'?": "william shakespeare",
    "What is the tallest building in the world?": "burj khalifa",
    "What is the largest desert in the world?": "sahara desert",
    "What is the primary language spoken in Brazil?": "portuguese",
    "What is the fastest bird?": "peregrine falcon",
    "How many sides does a hexagon have?": "6",
    "Who is the author of 'Harry Potter'?": "j.k. rowling",
    "What is the capital of Australia?": "canberra",
    "What is the square root of 64?": "8",
    "What is the most populous country in the world?": "china",
    "What is the national flower of Japan?": "cherry blossom",
    "What is the capital of Italy?": "rome",
    "Which ocean is located to the east of Africa?": "indian ocean",
    "How many planets are in the solar system?": "8",
    "What is the chemical symbol for water?": "h2o",
    "Who invented the telephone?": "alexander graham bell",
    "What is the longest bone in the human body?": "femur",
    "Who is the founder of Microsoft?": "bill gates",
    "What is the largest country in the world by area?": "russia",
    "What is the currency of the United States?": "dollar",
    "What is the national animal of Canada?": "beaver",
    "Who discovered penicillin?": "alexander fleming",
    "What is the capital of Spain?": "madrid",
    "What is the second planet from the Sun?": "venus",
    "What is the highest-grossing movie of all time?": "avatar",
    "How many players are there on a standard soccer team?": "11",
    "What is the longest word in the English language?": "pneumonoultramicroscopicsilicovolcanoconiosis",
    "What is the hardest natural material found on Earth?": "diamond",
    "Who is known as the father of modern physics?": "albert einstein",
    "What is the capital of Germany?": "berlin",
    "What is the main ingredient in sushi?": "rice",
    "How many elements are in the periodic table?": "118",
    "What is the largest continent by area?": "asia",
    "What is the symbol for silver on the periodic table?": "ag",
    "Which planet is closest to the Sun?": "mercury",
    "Who was the first woman to fly solo across the Atlantic?": "amelia earhart",
    "What is the name of the longest mountain range in the world?": "andes",
    "Who was the first president of the United States?": "george washington",
    "What is the capital of India?": "new delhi",
    "How many states are in the United States?": "50",
    "What is the largest country in Africa?": "algeria",
    "What is the main gas in Earth's atmosphere?": "nitrogen",
    "What is the smallest bone in the human body?": "stapes",
    "Who invented the airplane?": "wright brothers",
    "What is the smallest planet in our solar system?": "mercury",
    "Which is the longest-running TV show?": "the simpsons",
    "Who painted the Sistine Chapel ceiling?": "michelangelo",
    "What is the capital of Russia?": "moscow",
    "What is the largest island in the world?": "greenland",
    "What is the highest mountain in Africa?": "mount kilimanjaro",
    "How many hearts does an octopus have?": "3",
    "What is the longest-running musical on Broadway?": "the phantom of the opera",
    "What is the currency of India?": "rupee",
    "Who is the Greek god of the sea?": "poseidon",
    "What is the most common blood type in humans?": "o positive",
    "How many hours are there in a day?": "24",
    "Who discovered America?": "christopher columbus",
    "What is the capital of Japan?": "tokyo",
    "What is the name of the nearest star to Earth?": "the sun",
    "How many seasons are in a year?": "4",
    "What is the capital of South Korea?": "seoul",
    "Who was the first woman to win a Nobel Prize?": "marie curie",
    "What is the chemical symbol for oxygen?": "o",
    "Who wrote 'The Great Gatsby'?": "f. scott fitzgerald",
    "What is the name of the world's largest rainforest?": "amazon rainforest",
    "Which animal is known as the king of the jungle?": "lion",
    "How many teeth do adult humans have?": "32",
    "What is the capital of Brazil?": "brasilia",
    "Which element has the atomic number 1?": "hydrogen",
    "Who is the author of 'Moby-Dick'?": "herman melville",
    "What is the largest city in the United States by population?": "new york city",
    "What is the name of the world's longest river?": "nile river",
    "How many inches are in a foot?": "12",
    "What is the freezing point of water in Fahrenheit?": "32°f",
    "What is the official language of China?": "mandarin",
    "What is the national bird of the United States?": "bald eagle",
    "Which fruit is known as the king of fruits?": "durian",
    "What is the highest-grossing video game of all time?": "minecraft",
    "What is the chemical symbol for helium?": "he",
    "How many continents are there?": "7",
    "Who is known as the father of modern chemistry?": "antoine lavoisier",
    "What is the longest-running animated TV show?": "the simpsons",
    "Who is the main character in 'The Lord of the Rings'?": "frodo baggins",
    "What is the chemical symbol for iron?": "fe",
    "What is the capital of Argentina?": "buenos aires",
    "Who was the 16th president of the United States?": "abraham lincoln",
    "What is the largest volcano in the world?": "mauna loa",
    "What is the capital of Egypt?": "cairo",
    "What is the capital of France?": "paris",
    "What is the tallest statue in the world?": "statue of unity",
    "How many planets are there in the solar system?": "8",
    "Who was the first woman to fly solo across the Atlantic Ocean?": "amelia earhart",
    "What is the symbol for potassium in the periodic table?": "k",
    "What is the main ingredient in a Caesar salad?": "romaine lettuce",
    "How many total teeth does a full set of adult teeth have?": "32",
    "Who created the theory of evolution?": "charles darwin",
    "Which country is home to the kangaroo?": "australia",
    "What is the hardest rock?": "diamond",
    "How many years are in a century?": "100",
    "What planet is closest to the Earth?": "venus",
    "What animal is known for its ability to change color?": "chameleon",
    "What is the highest mountain in the world?": "mount everest",
    "Who was the first woman to win a Nobel Prize in Chemistry?": "marie curie",
    "Who wrote 'To Kill a Mockingbird'?": "harper lee",
    "How many stripes are on the United States flag?": "13",
    "What is the capital of Japan?": "tokyo",
    "Which bird can mimic human speech?": "parrot",
    "What is the largest organ in the human body?": "skin",
    "Who developed the polio vaccine?": "jonas salk",
    "What is the square root of 81?": "9",
    "Which ocean is the largest?": "pacific ocean",
    "What is the name of the largest living bird?": "ostrich",
    "Which element is represented by the symbol O?": "oxygen",
    "What is the smallest planet in the solar system?": "mercury",
    "Which U.S. state is known as the Sunshine State?": "florida",
    "What is the capital of Italy?": "rome",
    "What is the main ingredient in sushi?": "rice",
    "Which country is famous for its pyramids?": "egypt",
    "How many bones are in the human body?": "206",
    "What is the longest river in the world?": "amazon river",
    "Who is the current CEO of Tesla?": "elon musk",
    "Which planet has the most moons in our solar system?": "jupiter",
    "What year did the Titanic sink?": "1912",
    "What is the smallest country in Africa?": "seychelles",
    "Which gas do plants absorb from the air for photosynthesis?": "carbon dioxide",
    "What is the longest river in Europe?": "volga river",
    "Who was the first woman to win the Nobel Peace Prize?": "bertha felicie von suttner",
    "Who invented the steam engine?": "james watt",
    "What is the capital of Switzerland?": "bern",
    "What is the deepest ocean in the world?": "pacific ocean",
    "Who was the first woman to fly solo around the world?": "amelia earhart",
    "Which element has the atomic number 6?": "carbon",
    "What is the capital of Mexico?": "mexico city",
    "Who was the first man to reach space?": "yuri gagarin",
    "Which is the longest animal in the world?": "blue whale",
    "What is the hardest metal on Earth?": "chromium",
    "Who was the first African-American president of the United States?": "barack obama",
    "Which country is known for inventing pizza?": "italy",
    "Who was the first woman to win a Nobel Prize in physics?": "marie curie",
    "Which city is known as the Big Apple?": "new york city",
    "Who painted the 'Starry Night'?": "vincent van gogh",
    "How many chambers does the human heart have?": "4",
    "What is the tallest waterfall in the world?": "angel falls",
    "What is the largest living species of lizard?": "komodo dragon",
    "Which country is famous for its kangaroos?": "australia",
    "What is the currency of South Korea?": "won",
    "What is the largest city in the world by population?": "tokyo",
    "What animal is known for its ability to regenerate limbs?": "axolotl",
    "Which country is home to the Great Barrier Reef?": "australia",
    "Who invented the first mechanical computer?": "charles babbage",
    "What is the square root of 144?": "12",
    "Which chemical element is the most abundant in Earth's crust?": "oxygen",
    "What is the capital of Argentina?": "buenos aires",
    "Who is the author of 'The Catcher in the Rye'?": "j.d. salinger",
    "What is the name of the largest coral reef in the world?": "great barrier reef",
    "Who discovered gravity?": "isaac newton",
    "What is the capital of Egypt?": "cairo",
    "Which ocean is located to the west of the United States?": "pacific ocean",
    "Who was the first woman to fly solo across the Atlantic Ocean?": "amelia earhart",
    "What is the name of the world's tallest mountain?": "mount everest",
    "Which bird is known for its colorful feathers and ability to mimic sounds?": "parrot",
    "What is the capital of Turkey?": "ankara",
    "Who was the first person to climb Mount Everest?": "sir edmund hillary",
    "What is the largest land animal?": "african elephant",
    "Who wrote 'The Hobbit'?": "j.r.r. tolkien",
    "What is the official language of Brazil?": "portuguese",
    "Which planet is known for having a ring system?": "saturn",
    "What is the smallest country in the world by population?": "vatican city",
    "What is the most spoken language in the world?": "mandarin chinese",
    "Who is the famous scientist who developed the theory of evolution?": "charles darwin",
    "What is the capital of Japan?": "tokyo",
    "Which continent is the Sahara Desert located on?": "africa",
    "What is the largest country by population?": "china",
    "Who painted the 'Persistence of Memory'?": "salvador dalí",
    "Which natural disaster is measured on the Richter scale?": "earthquake",
    "What is the capital of Italy?": "rome",
    "What year did World War I begin?": "1914",
    "Who was the first president of the United States?": "george washington",
    "What is the smallest planet in our solar system?": "mercury",
    "Who invented the first airplane?": "wright brothers",
    "What is the chemical symbol for sodium?": "na",
    "What is the longest-running Broadway musical?": "the phantom of the opera",
    "Who is known as the 'father of modern chemistry'?": "antoine lavoisier",
    "How many teeth does an adult human have?": "32",
    "What is the largest mammal?": "blue whale",
    "What is the currency of Brazil?": "real",
    "Which continent is known as the 'Dark Continent'?": "africa",
    "What is the tallest mountain in North America?": "denali",
    "What is the capital of Canada?": "ottawa",
    "Which language has the most words?": "english",
    "What is the main ingredient in chocolate?": "cocoa",
    "Who invented the first successful vaccine?": "edward jenner",
    "What is the hardest rock in the world?": "diamond",
    "What is the currency of Russia?": "ruble",
    "Who is known as the father of modern physics?": "albert einstein",
    "Which country is the Eiffel Tower located in?": "france",
    "What is the capital of China?": "beijing",
    "Who wrote 'Pride and Prejudice'?": "jane austen",
    "What is the largest country in South America?": "brazil",
    "What is the currency of South Africa?": "rand",
    "Which fruit is known for keeping doctors away?": "apple",
    "How many colors are in a rainbow?": "7",
    "Which animal is known as the king of the jungle?": "lion",
    "What is the most famous pyramid in Egypt?": "great pyramid of giza",
    "What is the fastest animal in the world?": "cheetah",
    "What is the capital of Spain?": "madrid",
    "Who was the first person to walk on the Moon?": "neil armstrong",
    "What is the currency of India?": "rupee",
    "Which animal can live both in water and on land?": "amphibian",
    "What is the capital of France?": "paris",
    "Which scientist developed the theory of relativity?": "albert einstein",
    "How many bones are in a human body?": "206",
    "What is the name of the largest planet in our solar system?": "jupiter",
    "Which country is known for its tulips and windmills?": "netherlands",
    "What is the national flower of India?": "lotus",
    "Which country invented the game of chess?": "india",
    "What is the name of the smallest bone in the human body?": "stapes",
    "What is the largest volcano on Earth?": "mauna loa",
    "Which country is the birthplace of the Olympic Games?": "greece",
    "Who discovered penicillin?": "alexander fleming",
    "What is the longest bone in the human body?": "femur",
    "Who was the first woman to win the Nobel Prize in Chemistry?": "marie curie",
    "What is the chemical symbol for potassium?": "k",
    "Who is the father of modern physics?": "albert einstein",
    "What is the capital of Canada?": "ottawa",
    "Which is the smallest ocean in the world?": "arctic ocean",
    "What is the largest island in the world?": "greenland",
    "Who invented the telephone?": "alexander graham bell",
    "Which planet has the shortest day?": "jupiter",
    "What is the largest country in Africa?": "algeria",
    "What is the capital of Australia?": "canberra",
    "Who discovered electricity?": "benjamin franklin",
    "Which animal is known as the ship of the desert?": "camel",
    "What is the smallest continent?": "australia",
    "What is the national flower of Japan?": "cherry blossom",
    "What is the capital of Italy?": "rome",
    "Who was the first woman in space?": "valentina tereshkova",
    "Which country is famous for sushi?": "japan",
    "What is the largest country by area?": "russia",
    "Which sea is the largest in the world?": "philippine sea",
    "What is the capital of Brazil?": "brasilia",
    "Who developed the theory of general relativity?": "albert einstein",
    "What is the chemical symbol for silver?": "ag",
    "What is the longest river in North America?": "mississippi river",
    "What is the name of the largest coral reef system?": "great barrier reef",
    "Which country is known for the Eiffel Tower?": "france",
    "What is the smallest bone in the human body?": "stapes",
    "Which continent is also a country?": "australia",
    "Which country invented the paper?": "china",
    "What is the hardest natural material?": "diamond",
    "Who is known as the father of modern chemistry?": "antoine lavoisier",
    "What is the currency of Japan?": "yen",
    "What is the largest volcano on Earth?": "mauna loa",
    "Which country is home to the Great Barrier Reef?": "australia",
    "Who is the famous scientist who developed the theory of evolution?": "charles darwin",
    "What is the chemical symbol for oxygen?": "o",
    "Which planet is known as the Red Planet?": "mars",
    "What is the main ingredient in guacamole?": "avocado",
    "What is the capital of Spain?": "madrid",
    "Who wrote 'The Great Gatsby'?": "f. scott fitzgerald",
    "What is the capital of Russia?": "moscow",
    "What is the chemical symbol for water?": "h2o",
    "What is the fastest land animal?": "cheetah",
    "What is the capital of South Korea?": "seoul",
    "Who was the first person to walk on the Moon?": "neil armstrong",
    "What is the hardest material on Earth?": "diamond",
    "What is the fastest bird?": "peregrine falcon",
    "What is the national animal of the United States?": "bald eagle",
    "Which ocean is the largest in the world?": "pacific ocean",
    "What is the longest bone in the human body?": "femur",
    "What is the capital of China?": "beijing",
    "Which animal is known for its ability to regenerate limbs?": "axolotl",
    "Who invented the light bulb?": "thomas edison",
    "What is the smallest country in the world?": "vatican city",
    "What is the largest city in the United States by population?": "new york city",
    "What is the capital of Germany?": "berlin",
    "Who painted the 'Mona Lisa'?": "leonardo da vinci",
    "How many planets are in our solar system?": "8",
    "What is the name of the largest desert in the world?": "sahara desert",
    "Who was the first African-American president of the United States?": "barack obama",
    "What is the tallest mountain in the world?": "mount everest",
    "Who wrote 'Romeo and Juliet'?": "william shakespeare",
    "What is the capital of South Africa?": "pretoria",
    "What is the national flower of the United States?": "rose",
    "Which ocean lies to the east of Africa?": "indian ocean",
    "Who is the father of modern physics?": "albert einstein",
    "What is the currency of Mexico?": "peso",
    "What is the smallest planet in the solar system?": "mercury",
    "Which animal is known as the king of the jungle?": "lion",
    "What is the capital of Greece?": "athens",
    "Who invented the airplane?": "wright brothers",
    "What is the square root of 121?": "11",
    "What is the largest animal on Earth?": "blue whale",
    "What is the tallest building in the world?": "burj khalifa",
    "Who discovered the law of gravity?": "isaac newton",
    "What is the chemical symbol for gold?": "au",
    "Which animal is known for being the largest land mammal?": "african elephant",
    "What is the currency of the United Kingdom?": "pound",
    "What is the longest running TV show?": "the simpsons",
    "Who was the first woman to fly solo across the Atlantic?": "amelia earhart",
    "What is the capital of the United Kingdom?": "london",
    "What is the largest continent?": "asia",
    "What is the longest river in the world?": "amazon river",
    "What is the chemical symbol for carbon?": "c",
    "Who is the author of 'Moby-Dick'?": "herman melville",
    "What is the tallest waterfall in the world?": "angel falls",
    "Which bird is known for its beautiful tail feathers?": "peacock",
    "What is the highest mountain in Africa?": "mount kilimanjaro",
    "What is the chemical symbol for helium?": "he",
    "What is the square root of 64?": "8",
    "Which element is the most abundant in the Earth's crust?": "oxygen",
    "Who wrote 'The Catcher in the Rye'?": "j.d. salinger",
    "Which continent is the Sahara Desert located on?": "africa",
    "What is the currency of the United States?": "dollar",
    "What is the capital of Japan?": "tokyo",
    "Which bird can fly backward?": "hummingbird",
    "Who invented the first mechanical computer?": "charles babbage",
    "What is the largest desert in the world?": "sahara desert",
    "What is the capital of Mexico?": "mexico city",
    "Which element has the atomic number 1?": "hydrogen",
    "What is the highest-grossing movie of all time?": "avatar",
    "Who painted the 'Starry Night'?": "vincent van gogh",
    "How many sides does a hexagon have?": "6",
    "Which planet is closest to the Sun?": "mercury",
    "What is the tallest building in the world?": "burj khalifa",
    "Who invented the polio vaccine?": "jonas salk",
    "What is the chemical symbol for sodium?": "na",
    "Who is the author of 'The Lord of the Rings'?": "j.r.r. tolkien",
    "What is the main gas in Earth's atmosphere?": "nitrogen",
    "Which ocean is to the east of the United States?": "atlantic ocean",
    "How many hours are in a day?": "24",
    "What is the largest city in the world by population?": "tokyo",
    "What is the name of the tallest tree in the world?": "hyperion",
    "What is the square root of 49?": "7",
    "What is the capital of France?": "paris",
    "Who invented the light bulb?": "thomas edison",
    "What is the tallest mountain in the world?": "mount everest",
    "What is the largest country in the world by area?": "russia",
    "What is the longest river in the world?": "amazon river",
    "Who wrote '1984'?": "george orwell",
    "What is the capital of Italy?": "rome",
    "What is the fastest animal in the world?": "cheetah",
    "What is the longest bone in the human body?": "femur",
    "What is the capital of Japan?": "tokyo",
    "What is the smallest planet in the solar system?": "mercury",
    "Who discovered gravity?": "isaac newton",
    "Which country is known for the Eiffel Tower?": "france",
    "What is the currency of China?": "yuan",
    "What is the capital of Germany?": "berlin",
    "Who painted the 'Mona Lisa'?": "leonardo da vinci",
    "What is the largest island in the world?": "greenland",
    "What is the most spoken language in the world?": "mandarin chinese",
    "What is the currency of the United Kingdom?": "pound",
    "What animal is known as the 'King of the Jungle'?": "lion",
    "Who wrote 'To Kill a Mockingbird'?": "harper lee",
    "What is the smallest country in the world?": "vatican city",
    "Which ocean is the largest in the world?": "pacific ocean",
    "Who was the first president of the United States?": "george washington",
    "Which country is home to the Great Barrier Reef?": "australia",
    "What is the most famous pyramid in Egypt?": "great pyramid of giza",
    "What is the chemical symbol for gold?": "au",
    "Who was the first man on the moon?": "neil armstrong",
    "What is the square root of 64?": "8",
    "What is the largest country by population?": "china",
    "What is the currency of Japan?": "yen",
    "Who wrote 'The Catcher in the Rye'?": "j.d. salinger",
    "What is the hardest natural material?": "diamond",
    "Which bird can fly backward?": "hummingbird",
    "What is the capital of Canada?": "ottawa",
    "Who developed the theory of relativity?": "albert einstein",
    "What is the national animal of Australia?": "kangaroo",
    "What is the largest mammal on Earth?": "blue whale",
    "What is the main ingredient in a traditional Japanese sushi roll?": "rice",
    "What is the smallest continent?": "australia",
    "Who invented the telephone?": "alexander graham bell",
    "Which country is famous for its kangaroos?": "australia",
    "Who wrote 'Pride and Prejudice'?": "jane austen",
    "What is the chemical symbol for water?": "h2o",
    "What is the currency of Brazil?": "real",
    "What is the largest desert in the world?": "sahara desert",
    "What is the deepest ocean on Earth?": "pacific ocean",
    "What is the name of the longest river in the world?": "amazon river",
    "What is the capital of Egypt?": "cairo",
    "Who invented the first mechanical computer?": "charles babbage",
    "What is the national flower of India?": "lotus",
    "What is the chemical symbol for silver?": "ag",
    "Which animal is known for its ability to regenerate limbs?": "axolotl",
    "What is the largest country in Africa?": "algeria",
    "What is the square root of 144?": "12",
    "What is the largest planet in the solar system?": "jupiter",
    "What is the national animal of the United States?": "bald eagle",
    "Which bird is known for its beautiful tail feathers?": "peacock",
    "What is the capital of South Korea?": "seoul",
    "What is the longest-running TV show in the world?": "the simpsons",
    "Which country is the birthplace of chess?": "india",
    "What is the longest running Broadway musical?": "the phantom of the opera",
    "Who was the first woman to fly solo across the Atlantic?": "amelia earhart",
    "What is the capital of Russia?": "moscow",
    "Which animal is known as the ship of the desert?": "camel",
    "What is the capital of Mexico?": "mexico city",
    "Who discovered penicillin?": "alexander fleming",
    "What is the name of the first manned mission to the moon?": "apollo 11",
    "What is the largest ocean on Earth?": "pacific ocean",
    "What is the tallest waterfall in the world?": "angel falls",
    "What is the longest river in Africa?": "nile river",
    "What is the currency of South Korea?": "won",
    "Who developed the first successful polio vaccine?": "jonas salk",
    "What is the capital of Turkey?": "ankara",
    "What is the most spoken language in the world?": "mandarin chinese",
    "Which continent is known as the 'dark continent'?": "africa",
    "Who is known as the father of modern physics?": "albert einstein",
    "What is the fastest land animal?": "cheetah",
    "What is the capital of Brazil?": "brasilia",
    "Which country is home to the Great Wall of China?": "china",
    "Who painted the 'Starry Night'?": "vincent van gogh",
    "What is the largest city in the world by population?": "tokyo",
    "What is the square root of 49?": "7",
    "What is the hardest metal on Earth?": "chromium",
    "Who was the first woman to win the Nobel Peace Prize?": "bertha felicie von suttner",
    "What is the largest country in South America?": "brazil",
    "What is the capital of Greece?": "athens",
    "What is the currency of India?": "rupee",
    "What is the currency of Canada?": "canadian dollar",
    "Which country has the largest population?": "china",
    "What is the longest bone in the human body?": "femur",
    "Who wrote 'The Lord of the Rings'?": "j.r.r. tolkien",
    "What is the largest land animal?": "african elephant",
    "What is the smallest country in Africa?": "seychelles",
    "Who is known as the father of modern chemistry?": "antoine lavoisier",
    "What is the fastest bird in the world?": "peregrine falcon",
    "What is the capital of Australia?": "canberra",
    "What is the deepest point in the world's oceans?": "mariana trench",
    "What is the largest species of shark?": "whale shark",
    "What is the national flower of the United States?": "rose",
    "Which country is the birthplace of the Olympic Games?": "greece",
    "What is the currency of Russia?": "ruble",
    "What is the tallest building in the United States?": "one world trade center",
    "What is the chemical symbol for potassium?": "k",
    "Which country is known for tulips?": "netherlands",
    "What is the largest animal on Earth?": "blue whale",
    "What is the capital of South Africa?": "pretoria",
    "What is the chemical symbol for iron?": "fe",
    "Which country is home to the Eiffel Tower?": "france",
    "What is the capital of the United States?": "washington d.c.",
    "What is the largest country in South America?": "brazil",
    "Who invented the first successful airplane?": "wright brothers",
    "What is the smallest ocean in the world?": "arctic ocean",
    "What is the largest desert in the world?": "sahara desert",
    "What is the national animal of Canada?": "beaver",
    "What is the highest mountain in North America?": "denali",
    "What is the longest bone in the human body?": "femur",
    "Which planet is closest to the Sun?": "mercury",
    "What is the main ingredient in guacamole?": "avocado",
    "Who was the first man to reach the South Pole?": "roald amundsen",
    "What is the national fruit of India?": "mango",
    "What is the capital of Argentina?": "buenos aires",
    "Which planet is known as the Red Planet?": "mars",
    "What is the name of the largest ocean on Earth?": "pacific ocean",
    "What is the tallest building in the world?": "burj khalifa",
    "Who invented the telephone?": "alexander graham bell",
    "What is the capital of India?": "new delhi",
    "What is the largest animal on Earth?": "blue whale",
    "Who was the first woman to fly solo across the Atlantic?": "amelia earhart",
    "What is the capital of Brazil?": "brasilia",
    "Who is the author of 'The Hobbit'?": "j.r.r. tolkien",
    "Which bird is known for its beautiful tail feathers?": "peacock",
    "What is the longest river in Europe?": "volga river",
    "What is the capital of Egypt?": "cairo",
    "What is the currency of Germany?": "euro",
    "Which country is known for its tulips?": "netherlands",
    "Who painted the 'Last Supper'?": "leonardo da vinci",
    "What is the hardest natural substance on Earth?": "diamond",
    "What is the longest river in Africa?": "nile river",
    "What is the chemical symbol for silver?": "ag",
    "What is the capital of China?": "beijing",
    "What is the fastest land animal?": "cheetah",
    "What is the largest island in the world?": "greenland",
    "Which country is famous for sushi?": "japan",
    "What is the square root of 25?": "5",
    "What is the currency of France?": "euro",
    "Which ocean is to the east of Africa?": "indian ocean",
    "What is the longest mountain range in the world?": "andes mountains",
    "Who is known as the father of modern chemistry?": "antoine lavoisier",
    "What is the currency of the United Kingdom?": "pound",
    "What is the largest volcano on Earth?": "mauna loa",
    "Who is the father of modern physics?": "albert einstein",
    "What is the largest city in the United States by population?": "new york city",
    "What is the national bird of the United States?": "bald eagle",
    "What is the capital of Japan?": "tokyo",
    "What is the longest-running TV show?": "the simpsons",
    "What is the main ingredient in falafel?": "chickpeas",
    "What is the chemical symbol for copper?": "cu",
    "What is the largest country by area?": "russia",
    "What is the currency of Australia?": "australian dollar",
    "Which planet is known as the gas giant?": "jupiter",
    "What is the smallest country in Africa?": "seychelles",
    "Who wrote 'Moby-Dick'?": "herman melville",
    "What is the largest continent by area?": "asia",
    "What is the capital of Canada?": "ottawa",
    "Who invented the first mechanical computer?": "charles babbage",
    "What is the chemical symbol for oxygen?": "o",
    "What is the capital of Mexico?": "mexico city",
    "Who discovered the law of gravity?": "isaac newton",
    "What is the currency of India?": "rupee",
    "What is the main ingredient in hummus?": "chickpeas",
    "What is the smallest bone in the human body?": "stapes",
    "Which ocean is to the west of the United States?": "pacific ocean",
    "What is the capital of Italy?": "rome",
    "Which planet is known as the Earth's twin?": "venus",
    "What is the chemical symbol for nitrogen?": "n",
    "Who wrote 'War and Peace'?": "leo tolstoy",
    "What is the national animal of the United Kingdom?": "lion",
    "What is the largest species of bear?": "polar bear",
    "What is the chemical symbol for sodium?": "na",
    "What is the capital of South Korea?": "seoul",
    "What is the largest city in Japan?": "tokyo",
    "What is the longest-running Broadway musical?": "the phantom of the opera",
    "What is the national animal of China?": "giant panda",
    "What is the currency of Japan?": "yen",
    "Which country is the birthplace of the Olympic Games?": "greece",
    "What is the tallest building in the United States?": "one world trade center",
    "Who developed the first successful polio vaccine?": "jonas salk",
    "What is the chemical symbol for potassium?": "k",
    "What is the currency of Mexico?": "peso",
    "What is the largest river in North America?": "mississippi river",
    "What is the chemical symbol for mercury?": "hg",
    "What is the capital of Greece?": "athens",
    "What is the square root of 81?": "9",
    "What is the largest species of shark?": "whale shark",
    "What is the national flower of Japan?": "cherry blossom",
    "What is the capital of Russia?": "moscow",
    "Who painted the 'Starry Night'?": "vincent van gogh",
    "What is the square root of 16?": "4",
    "Which country is famous for pizza?": "italy",
    "What is the capital of South Africa?": "pretoria",
    "What is the longest river in Asia?": "yangtze river",
    "What is the largest planet in the solar system?": "jupiter",
    "Who was the first woman to win a Nobel Prize?": "marie curie",
    "What is the smallest country in Europe?": "vatican city",
    "What is the largest city in the world by area?": "hulunbuir",
    "What is the capital of Spain?": "madrid",
    "What is the hardest substance found in nature?": "diamond",
    "Which continent has the most countries?": "africa",
    "What is the capital of Egypt?": "cairo",
    "Who developed the theory of evolution?": "charles darwin",
    "What is the chemical symbol for aluminum?": "al",
    "What is the largest country in Europe?": "russia",
    "Who was the first person to reach the North Pole?": "robert peary",
    "What is the national sport of Japan?": "sumo wrestling",
    "What is the largest desert in the world?": "sahara desert",
    "What is the tallest mountain in North America?": "denali",
    "What is the chemical symbol for lead?": "pb",
    "What is the currency of South Africa?": "rand",
    "What is the chemical symbol for mercury?": "hg",
    "Who invented the first airplane?": "wright brothers",
    "What is the longest river in the world?": "amazon river",
    "What is the capital of India?": "new delhi",
    "Who is known as the father of modern physics?": "albert einstein",
    "Which planet is known as the Red Planet?": "mars",
    "What is the smallest country in the world?": "vatican city",
    "What is the capital of Australia?": "canberra",
    "What is the chemical symbol for potassium?": "k",
    "What is the largest ocean in the world?": "pacific ocean",
    "What is the tallest waterfall in the world?": "angel falls",
    "Which country is known for its chocolate?": "belgium",
    "What is the longest-running TV series in the world?": "the simpsons",
    "What is the capital of the United Kingdom?": "london",
    "Who wrote 'Don Quixote'?": "miguel de cervantes",
    "What is the chemical symbol for calcium?": "ca",
    "What is the currency of Brazil?": "real",
    "Who discovered penicillin?": "alexander fleming",
    "What is the largest city in the world by population?": "tokyo",
    "Who invented the telephone?": "alexander graham bell",
    "What is the name of the tallest tree in the world?": "hyperion",
    "Who wrote 'The Great Gatsby'?": "f. scott fitzgerald",
    "Which bird can fly backward?": "hummingbird",
    "What is the smallest planet in the solar system?": "mercury",
    "What is the capital of Canada?": "ottawa",
    "What is the tallest building in the world?": "burj khalifa",
    "What is the main ingredient in guacamole?": "avocado",
    "What is the capital of Russia?": "moscow",
    "Who invented the light bulb?": "thomas edison",
    "Which country is home to the Eiffel Tower?": "france",
    "Who discovered electricity?": "benjamin franklin",
    "What is the longest river in Asia?": "yangtze river",
    "Who painted the 'Mona Lisa'?": "leonardo da vinci",
    "What is the currency of the United Kingdom?": "pound",
    "What is the smallest ocean in the world?": "arctic ocean",
    "What is the largest coral reef system in the world?": "great barrier reef",
    "Who developed the theory of general relativity?": "albert einstein",
    "What is the capital of Brazil?": "brasilia",
    "Who was the first person to walk on the Moon?": "neil armstrong",
    "What is the chemical symbol for water?": "h2o",
    "What is the tallest mountain in the world?": "mount everest",
    "What is the largest species of shark?": "whale shark",
    "What is the currency of India?": "rupee",
    "What is the fastest bird?": "peregrine falcon",
    "What is the smallest bone in the human body?": "stapes",
    "What is the capital of South Korea?": "seoul",
    "What is the fastest land animal?": "cheetah",
    "Who painted the 'Starry Night'?": "vincent van gogh",
    "What is the largest city in the United States?": "new york city",
    "What is the deepest point on Earth?": "mariana trench",
    "Who is the first African-American president of the United States?": "barack obama",
    "What is the chemical symbol for carbon?": "c",
    "What is the name of the longest river in Africa?": "nile river",
    "Who was the first woman in space?": "valentina tereshkova",
    "What is the square root of 121?": "11",
    "What is the largest city in Japan?": "tokyo",
    "What is the hardest metal on Earth?": "chromium",
    "What is the longest running Broadway show?": "the phantom of the opera",
    "Who wrote 'The Catcher in the Rye'?": "j.d. salinger",
    "What is the largest species of bear?": "polar bear",
    "What is the largest continent?": "asia",
    "What is the fastest fish in the ocean?": "black marlin",
    "What is the chemical symbol for silver?": "ag",
    "Who is the author of 'The Lord of the Rings'?": "j.r.r. tolkien",
    "What is the largest mammal?": "blue whale",
    "What is the smallest continent?": "australia",
    "Who invented the first computer?": "charles babbage",
    "What is the national flower of the United States?": "rose",
    "What is the currency of Mexico?": "peso",
    "What is the tallest building in the United States?": "one world trade center",
    "What is the longest running TV show?": "the simpsons",
    "Who painted the 'Last Supper'?": "leonardo da vinci",
    "What is the capital of China?": "beijing",
    "What is the chemical symbol for potassium?": "k",
    "What is the currency of Russia?": "ruble",
    "What is the name of the largest moon of Saturn?": "titan",
    "Which animal is known for its ability to change colors?": "chameleon",
    "What is the rarest blood type in the world?": "rh-null",
    "What is the national flower of the United States?": "rose",
    "What element is diamond made of?": "carbon",
    "What is the capital of Iceland?": "reykjavik",
    "Who was the first woman to fly solo around the world?": "amelia earhart",
    "Which country is home to the kangaroo?": "australia",
    "What is the longest-running animated TV show?": "the simpsons",
    "Who was the first woman to receive a medical degree in the United States?": "elizabeth blackwell",
    "What is the only country that is also a continent?": "australia",
    "Which ocean is the world's largest?": "pacific ocean",
    "What is the chemical symbol for the element with atomic number 1?": "h",
    "What is the tallest breed of dog in the world?": "great dane",
    "Which bird is known for being able to mimic human speech?": "african grey parrot",
    "What is the name of the longest river in the world according to some sources?": "amazon river",
    "What is the world's largest freshwater lake by area?": "lake superior",
    "Which country has the most pyramids?": "sudan",
    "What is the tallest mountain in the solar system?": "olympus mons",
    "What is the capital of Mongolia?": "ulaanbaatar",
    "What is the fastest growing plant in the world?": "bamboo",
    "What is the name of the longest-running film series?": "james bond",
    "Who was the first female prime minister of the United Kingdom?": "margaret thatcher",
    "Which animal has the longest lifespan?": "bowhead whale",
    "Which planet has the most moons in our solar system?": "jupiter",
    "What is the official language of Brazil?": "portuguese",
    "What is the largest species of penguin?": "emperor penguin",
    "Which country is the world's largest producer of chocolate?": "ivory coast",
    "What is the fastest bird in the world?": "peregrine falcon",
    "Which fruit has its seeds on the outside?": "strawberry",
    "What is the capital of Argentina?": "buenos aires",
    "Which famous scientist developed the three laws of motion?": "isaac newton",
    "Which country is known for inventing paper?": "china",
    "Who painted the 'Girl with a Pearl Earring'?": "johannes vermeer",
    "What is the largest island in the Caribbean?": "cuba",
    "Which animal is the symbol of the World Wildlife Fund?": "giant panda",
    "What is the smallest bird in the world?": "bee hummingbird",
    "Which country has the longest coastline in the world?": "canada",
    "What is the national animal of Scotland?": "unicorn",
    "What is the deepest oceanic trench in the world?": "mariana trench",
    "Which planet is known as the morning star?": "venus",
    "What is the main ingredient in sushi?": "rice",
    "What is the national sport of Canada?": "ice hockey",
    "What is the capital of Turkey?": "ankara",
    "What is the name of the world's tallest waterfall?": "angel falls",
    "Which country is home to the Great Barrier Reef?": "australia",
    "Which country was the first to grant women the right to vote?": "new zealand",
    "What is the largest known species of tree?": "giant sequoia",
    "What is the name of the longest river in Europe?": "volga river",
    "Who was the first African-American woman to win a Nobel Prize?": "toni morrison",
    "What is the capital of New Zealand?": "wellington",
    "What is the world's largest coral reef system?": "great barrier reef",
    "What type of animal is the 'quokka'?": "marsupial",
    "What was the first country to use paper money?": "china",
    "What is the currency of South Korea?": "won",
    "What is the fastest growing plant in the world?": "bamboo",
    "What is the name of the largest desert in Asia?": "gobi desert",
    "Who wrote 'The Chronicles of Narnia'?": "c.s. lewis",
    "Which planet is known as the 'Ice Giant'?": "uranus",
    "What was the first artificial satellite sent into space?": "sputnik 1",
    "What is the smallest country in Africa?": "seychelles",
    "Who developed the theory of general relativity?": "albert einstein",
    "What is the name of the largest species of bear?": "polar bear",
    "Which element has the atomic number 6?": "carbon",
    "What is the capital of Denmark?": "copenhagen",
    "What is the name of the highest waterfall in the world?": "angel falls",
    "Which bird is known for migrating thousands of miles?": "arctic tern",
    "What is the national flower of India?": "lotus",
    "Which animal has the longest tongue in the world?": "giant anteater",
    "What is the name of the largest river in South America?": "amazon river",
    "What is the capital of Thailand?": "bangkok",
    "Who wrote 'To Kill a Mockingbird'?": "harper lee",
    "What is the smallest continent?": "australia",
    "What is the chemical symbol for iron?": "fe",
    "Who was the first woman to receive the Nobel Prize?": "marie curie",
    "Which ocean is the world's second largest?": "atlantic ocean",
    "What is the capital of Finland?": "helsinki",
    "What is the national animal of the United States?": "bald eagle",
    "Who was the first woman to fly solo across the Atlantic?": "amelia earhart",
    "What is the only bird that can fly backward?": "hummingbird",
    "Which country is known for inventing the first mechanical clock?": "china",
    "What is the rarest gemstone in the world?": "painite",
    "What animal has fingerprints that are almost identical to humans?": "koala",
    "Which animal can sleep for up to three years?": "snail",
    "What is the only planet in the solar system that rotates clockwise?": "venus",
    "What is the smallest country in Africa by area?": "seychelles",
    "Which tree produces acorns?": "oak tree",
    "What is the first color in a rainbow?": "red",
    "Which country has a city named 'Rome' other than Italy?": "united states",
    "Which fruit contains the most calories per 100 grams?": "avocado",
    "What is the name of the longest-running space station?": "international space station",
    "Which ocean is the saltiest?": "atlantic ocean",
    "Which animal is the fastest in water?": "black marlin",
    "What is the capital of the world's smallest country?": "vatican city",
    "Which fruit is known as the 'king of fruits' for its strong odor?": "durian",
    "What is the largest species of butterfly?": "atlas moth",
    "What is the only mammal capable of flight?": "bat",
    "Which planet is the hottest in the solar system?": "venus",
    "What was the first animal to be sent into space?": "laika the dog",
    "What is the name of the longest mountain range under the ocean?": "mid-ocean ridge",
    "Which bird has the largest wingspan?": "albatross",
    "Which insect is capable of lifting up to 50 times its body weight?": "dung beetle",
    "What is the tallest building in the world that is not located in Dubai?": "shanghai tower",
    "Which bird is the national bird of the United States?": "bald eagle",
    "What is the largest volcano in the solar system?": "olympus mons",
    "Which country has the most official languages?": "south africa",
    "What is the only continent that is entirely located in the Southern Hemisphere?": "australia",
    "What animal can hold its breath the longest underwater?": "sperm whale",
    "Which country has the most islands?": "sweden",
    "What is the smallest bone in the human body?": "stapes",
    "Which mammal can live without drinking water for its entire life?": "kangaroo rat",
    "What is the world's longest river according to recent measurements?": "amazon river",
    "What is the name of the deepest part of the world's oceans?": "mariana trench",
    "Which animal has the longest migration route?": "arctic tern",
    "What is the world's oldest known living organism?": "posidonia oceanica (a sea grass)",
    "Which city has the most number of bridges in the world?": "venice",
    "Which country has the most pyramids?": "sudan",
    "What is the name of the largest desert in the world?": "antarctica",
    "What is the only metal that is liquid at room temperature?": "mercury",
    "What is the only planet that rotates on its side?": "uranus",
    "Which animal is known to have the most complex eyes in the animal kingdom?": "mantis shrimp",
    "What is the rarest type of meteorite found on Earth?": "stony-iron meteorites",
    "Which animal can change its gender during its lifetime?": "clownfish",
    "What is the largest rodent in the world?": "capybara",
    "What is the name of the longest-living species of mammal?": "bowhead whale",
    "What is the only country that is also a continent?": "australia",
    "Which city is known as the 'City of a Hundred Spires'?": "prague",
    "What is the only insect that produces honey?": "honeybee",
    "What animal can go without water for weeks at a time?": "camel",
    "What is the capital of Bhutan, known for being the only carbon-negative country?": "thimphu",
    "What is the largest living organism on Earth?": "honey fungus in oregon",
    "Which planet is closest in size to Earth?": "venus",
    "Which mountain range is known as the 'roof of the world'?": "tibetan plateau",
    "What is the fastest bird in level flight?": "common swift",
    "Which animal is capable of producing the most electricity?": "electric eel",
    "What is the longest-living species of bird?": "albatross",
    "Which fruit is known to have the highest amount of potassium?": "banana",
    "What is the deepest point on Earth's surface?": "mariana trench",
    "Which country has no rivers?": "saudi arabia",
    "What is the only continent with no native human population?": "antarctica",
    "Which country has the most volcanoes?": "indonesia",
    "What is the largest living creature on Earth?": "blue whale",
    "Which planet has the longest day?": "venus",
    "What is the most commonly spoken language in the world?": "mandarin chinese",
    "What was the first artificial Earth satellite?": "sputnik 1",
    "Which country is known for its annual running of the bulls?": "spain",
    "What is the name of the only flag with a square shape?": "switzerland",
    "Which island country is home to the world's smallest capital city?": "nauru",
    "What is the capital of Kazakhstan, which replaced Almaty in 1997?": "nur-sultan",
    "Which planet has the shortest day in the solar system?": "jupiter",
    "Which species of jellyfish is considered biologically immortal?": "turritopsis dohrnii",
    "What was the first video game ever created?": "tennis for two",
    "What is the tallest waterfall in North America?": "yosemite falls",
    "Which fruit is known to have the highest vitamin C content?": "kiwifruit",
    "Which animal has the longest pregnancy?": "elephant",
    "Which country has the largest population of tigers?": "india",
    "What animal is the largest species of frog?": "goliath frog",
    "What is the capital of the only country that starts with the letter 'Q'?": "doha",
    "Which animal is known to have the most teeth?": "snail",
    "What is the most expensive liquid in the world?": "scorpion venom",
    "Which is the only continent that has no indigenous human population?": "antarctica",
    "Which planet has the most spectacular rings?": "saturn",
    "What is the longest recorded lifespan of a human being?": "jeanne calment",
    "What is the name of the longest mountain range under the ocean?": "mid-ocean ridge",
    "Which animal is capable of living for months without food?": "cockroach"
}






